package deezer

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// Settings holds runtime options for the Deezer subworker.
type Settings struct {
	Enabled   bool
	ARL       string
	URL       string // external deezer-downloader base URL; empty spawns a child process
	Port      int
	Quality   string
	Command   string
	MusicDir  string
	ConfigDir string
}

func (s Settings) ConfigPath() string {
	return filepath.Join(s.ConfigDir, "deezer-downloader.ini")
}

func (s Settings) SpawnURL() string {
	if s.URL != "" {
		return strings.TrimRight(s.URL, "/")
	}
	return fmt.Sprintf("http://127.0.0.1:%d", s.Port)
}

func (s Settings) Configured() bool {
	if strings.TrimSpace(s.URL) != "" {
		return true
	}
	return strings.TrimSpace(s.ARL) != ""
}

// WriteConfig renders deezer-downloader.ini with downloads going into musicDir.
func WriteConfig(path string, musicDir, arl, quality, ytDLP string, port int) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	if quality != "mp3" && quality != "flac" {
		quality = "mp3"
	}
	if port <= 0 {
		port = 5001
	}

	body := fmt.Sprintf(`; Generated by Spook - do not edit while Spook is running.
[mpd]
use_mpd = False
host = localhost
port = 6600
music_dir_root = %s

[download_dirs]
base = %s
songs = %%(base)s/songs
albums = %%(base)s/albums
zips = %%(base)s/zips
playlists = %%(base)s/playlists
youtubedl = %%(base)s/youtube-dl

[debug]
command = echo "see spook logs"

[http]
host = 127.0.0.1
port = %d
url_prefix =
api_root = %%(url_prefix)s
static_root = %%(url_prefix)s/static

[proxy]
server =

[threadpool]
workers = 2

[deezer]
cookie_arl = %s
quality = %s

[youtubedl]
command = %s
`, iniEscape(musicDir), iniEscape(musicDir), port, iniEscape(sanitizeARL(arl)), quality, iniEscape(ytDLP))

	return os.WriteFile(path, []byte(body), 0o600)
}

func iniEscape(value string) string {
	return strings.ReplaceAll(value, "\n", "")
}

func sanitizeARL(arl string) string {
	arl = strings.TrimSpace(arl)
	if idx := strings.Index(arl, "#"); idx >= 0 {
		arl = strings.TrimSpace(arl[:idx])
	}
	var b strings.Builder
	for _, r := range arl {
		switch {
		case r >= '0' && r <= '9', r >= 'a' && r <= 'f', r >= 'A' && r <= 'F':
			b.WriteRune(r)
		}
	}
	return b.String()
}

func findExecutable(fallbacks ...string) string {
	for _, name := range fallbacks {
		if path, err := exec.LookPath(name); err == nil {
			return path
		}
	}
	if len(fallbacks) > 0 {
		return fallbacks[len(fallbacks)-1]
	}
	return ""
}
